package org.iosclone.keyboard.emoji

object EmojiData {

    val allEmojis: List<EmojiItem> = listOf(
        // Smileys & Emotion
        EmojiItem("😀", "Grinning Face", EmojiCategory.SMILEYS, listOf("smile", "happy", "joy", "grin")),
        EmojiItem("😃", "Grinning Face with Big Eyes", EmojiCategory.SMILEYS, listOf("smile", "happy", "joy")),
        EmojiItem("😄", "Grinning Face with Smiling Eyes", EmojiCategory.SMILEYS, listOf("happy", "laugh", "joy")),
        EmojiItem("😁", "Beaming Face with Smiling Eyes", EmojiCategory.SMILEYS, listOf("teeth", "grin", "happy")),
        EmojiItem("😆", "Grinning Squinting Face", EmojiCategory.SMILEYS, listOf("laugh", "happy", "haha", "xd")),
        EmojiItem("😅", "Grinning Face with Sweat", EmojiCategory.SMILEYS, listOf("sweat", "nervous", "relief")),
        EmojiItem("😂", "Face with Tears of Joy", EmojiCategory.SMILEYS, listOf("cry", "laugh", "lol", "crying", "funny", "joy")),
        EmojiItem("🤣", "Rolling on the Floor Laughing", EmojiCategory.SMILEYS, listOf("rofl", "lol", "funny", "laugh")),
        EmojiItem("🥹", "Face Holding Back Tears", EmojiCategory.SMILEYS, listOf("tears", "gratitude", "moved", "proud")),
        EmojiItem("☺️", "Smiling Face", EmojiCategory.SMILEYS, listOf("blush", "smile", "warm")),
        EmojiItem("😊", "Smiling Face with Smiling Eyes", EmojiCategory.SMILEYS, listOf("blush", "proud", "happy")),
        EmojiItem("😇", "Smiling Face with Halo", EmojiCategory.SMILEYS, listOf("angel", "innocent", "halo")),
        EmojiItem("🙂", "Slightly Smiling Face", EmojiCategory.SMILEYS, listOf("smile", "okay")),
        EmojiItem("🙃", "Upside-Down Face", EmojiCategory.SMILEYS, listOf("sarcasm", "silly", "irony")),
        EmojiItem("😉", "Winking Face", EmojiCategory.SMILEYS, listOf("wink", "flirt")),
        EmojiItem("😌", "Relieved Face", EmojiCategory.SMILEYS, listOf("relieved", "calm", "peace")),
        EmojiItem("😍", "Smiling Face with Heart-Eyes", EmojiCategory.SMILEYS, listOf("love", "heart", "crush", "adoration")),
        EmojiItem("🥰", "Smiling Face with Hearts", EmojiCategory.SMILEYS, listOf("love", "in love", "hearts", "affection")),
        EmojiItem("😘", "Face Blowing a Kiss", EmojiCategory.SMILEYS, listOf("kiss", "love", "affection")),
        EmojiItem("😗", "Kissing Face", EmojiCategory.SMILEYS, listOf("kiss")),
        EmojiItem("😙", "Kissing Face with Smiling Eyes", EmojiCategory.SMILEYS, listOf("kiss", "smile")),
        EmojiItem("😚", "Kissing Face with Closed Eyes", EmojiCategory.SMILEYS, listOf("kiss", "blush")),
        EmojiItem("😋", "Face Savoring Food", EmojiCategory.SMILEYS, listOf("yummy", "delicious", "tongue")),
        EmojiItem("😛", "Face with Tongue", EmojiCategory.SMILEYS, listOf("tongue", "playful")),
        EmojiItem("😜", "Winking Face with Tongue", EmojiCategory.SMILEYS, listOf("crazy", "party", "tongue", "wink")),
        EmojiItem("🤪", "Zany Face", EmojiCategory.SMILEYS, listOf("crazy", "wild", "goofy")),
        EmojiItem("😝", "Squinting Face with Tongue", EmojiCategory.SMILEYS, listOf("tongue", "laugh", "playful")),
        EmojiItem("🤑", "Money-Mouth Face", EmojiCategory.SMILEYS, listOf("money", "rich", "dollar")),
        EmojiItem("🤗", "Smiling Face with Open Hands", EmojiCategory.SMILEYS, listOf("hug", "warmth")),
        EmojiItem("🫣", "Face with Peeking Eye", EmojiCategory.SMILEYS, listOf("peek", "shy", "scared")),
        EmojiItem("🤫", "Shushing Face", EmojiCategory.SMILEYS, listOf("quiet", "secret", "shh")),
        EmojiItem("🤔", "Thinking Face", EmojiCategory.SMILEYS, listOf("think", "ponder", "hmm", "curious")),
        EmojiItem("🫡", "Saluting Face", EmojiCategory.SMILEYS, listOf("salute", "respect", "yes sir")),
        EmojiItem("🤐", "Zipper-Mouth Face", EmojiCategory.SMILEYS, listOf("secret", "zip", "quiet")),
        EmojiItem("🤨", "Face with Raised Eyebrow", EmojiCategory.SMILEYS, listOf("suspicious", "doubt", "skeptical")),
        EmojiItem("😐", "Neutral Face", EmojiCategory.SMILEYS, listOf("meh", "blank", "neutral")),
        EmojiItem("😑", "Expressionless Face", EmojiCategory.SMILEYS, listOf("expressionless", "bored")),
        EmojiItem("😶", "Face Without Mouth", EmojiCategory.SMILEYS, listOf("speechless", "silent")),
        EmojiItem("🫥", "Dotted Line Face", EmojiCategory.SMILEYS, listOf("invisible", "hidden", "disappear")),
        EmojiItem("😏", "Smirking Face", EmojiCategory.SMILEYS, listOf("smirk", "flirt", "smug")),
        EmojiItem("😒", "Unamused Face", EmojiCategory.SMILEYS, listOf("unamused", "bored", "displeased")),
        EmojiItem("🙄", "Face with Rolling Eyes", EmojiCategory.SMILEYS, listOf("eyeroll", "whatever", "sarcasm")),
        EmojiItem("😬", "Grimacing Face", EmojiCategory.SMILEYS, listOf("grimace", "awkward", "oops")),
        EmojiItem("😮‍💨", "Face Exhaling", EmojiCategory.SMILEYS, listOf("sigh", "relief", "tired")),
        EmojiItem("🤥", "Lying Face", EmojiCategory.SMILEYS, listOf("lie", "pinocchio")),
        EmojiItem("🫠", "Melting Face", EmojiCategory.SMILEYS, listOf("melt", "hot", "embarrassed", "dissolve")),
        EmojiItem("😴", "Sleeping Face", EmojiCategory.SMILEYS, listOf("sleep", "tired", "zzz")),
        EmojiItem("🤤", "Drooling Face", EmojiCategory.SMILEYS, listOf("drool", "delicious")),
        EmojiItem("😪", "Sleepy Face", EmojiCategory.SMILEYS, listOf("sleepy", "tired")),
        EmojiItem("😵", "Face with Crossed-Out Eyes", EmojiCategory.SMILEYS, listOf("dizzy", "dead", "knocked out")),
        EmojiItem("🤯", "Exploding Head", EmojiCategory.SMILEYS, listOf("mind blown", "shock", "boom")),
        EmojiItem("🥳", "Partying Face", EmojiCategory.SMILEYS, listOf("party", "celebrate", "birthday", "cheers")),
        EmojiItem("😎", "Smiling Face with Sunglasses", EmojiCategory.SMILEYS, listOf("cool", "sunglasses", "boss")),
        EmojiItem("🤓", "Nerd Face", EmojiCategory.SMILEYS, listOf("nerd", "geek", "smart")),
        EmojiItem("🧐", "Face with Monocle", EmojiCategory.SMILEYS, listOf("monocle", "curious", "inspect")),
        EmojiItem("😕", "Confused Face", EmojiCategory.SMILEYS, listOf("confused", "puzzled")),
        EmojiItem("😟", "Worried Face", EmojiCategory.SMILEYS, listOf("worried", "nervous")),
        EmojiItem("🙁", "Slightly Frowning Face", EmojiCategory.SMILEYS, listOf("sad", "frown")),
        EmojiItem("😮", "Face with Open Mouth", EmojiCategory.SMILEYS, listOf("wow", "surprised")),
        EmojiItem("😯", "Hushed Face", EmojiCategory.SMILEYS, listOf("surprise", "stunned")),
        EmojiItem("😲", "Astonished Face", EmojiCategory.SMILEYS, listOf("shock", "astonished")),
        EmojiItem("😳", "Flushed Face", EmojiCategory.SMILEYS, listOf("embarrassed", "flushed", "blush")),
        EmojiItem("🥺", "Pleading Face", EmojiCategory.SMILEYS, listOf("puppy eyes", "please", "pleading", "beg")),
        EmojiItem("😦", "Frowning Face with Open Mouth", EmojiCategory.SMILEYS, listOf("shock", "sad")),
        EmojiItem("😨", "Fearful Face", EmojiCategory.SMILEYS, listOf("fear", "scared")),
        EmojiItem("😰", "Anxious Face with Sweat", EmojiCategory.SMILEYS, listOf("anxious", "sweat", "nervous")),
        EmojiItem("😥", "Sad but Relieved Face", EmojiCategory.SMILEYS, listOf("relieved", "sweat")),
        EmojiItem("😢", "Crying Face", EmojiCategory.SMILEYS, listOf("tear", "sad", "crying")),
        EmojiItem("😭", "Loudly Crying Face", EmojiCategory.SMILEYS, listOf("sob", "sad", "cry", "crying", "tears")),
        EmojiItem("😱", "Face Screaming in Fear", EmojiCategory.SMILEYS, listOf("scream", "scared", "horror")),
        EmojiItem("😖", "Confounded Face", EmojiCategory.SMILEYS, listOf("confounded", "frustrated")),
        EmojiItem("😣", "Persevering Face", EmojiCategory.SMILEYS, listOf("struggle", "persevere")),
        EmojiItem("😞", "Disappointed Face", EmojiCategory.SMILEYS, listOf("sad", "disappointed")),
        EmojiItem("😓", "Downcast Face with Sweat", EmojiCategory.SMILEYS, listOf("sweat", "tired")),
        EmojiItem("😩", "Weary Face", EmojiCategory.SMILEYS, listOf("weary", "tired", "stressed")),
        EmojiItem("😫", "Tired Face", EmojiCategory.SMILEYS, listOf("tired", "exhausted")),
        EmojiItem("🥱", "Yawning Face", EmojiCategory.SMILEYS, listOf("yawn", "sleepy", "bored")),
        EmojiItem("😤", "Face with Steam From Nose", EmojiCategory.SMILEYS, listOf("angry", "furious", "triumph")),
        EmojiItem("😡", "Enraged Face", EmojiCategory.SMILEYS, listOf("mad", "angry", "furious", "rage")),
        EmojiItem("😠", "Angry Face", EmojiCategory.SMILEYS, listOf("angry", "mad")),
        EmojiItem("🤬", "Face with Symbols on Mouth", EmojiCategory.SMILEYS, listOf("swear", "curse", "angry")),
        EmojiItem("😈", "Smiling Face with Horns", EmojiCategory.SMILEYS, listOf("devil", "evil", "naughty")),
        EmojiItem("👿", "Angry Face with Horns", EmojiCategory.SMILEYS, listOf("devil", "mad")),
        EmojiItem("💀", "Skull", EmojiCategory.SMILEYS, listOf("dead", "skull", "skeleton", "dying")),
        EmojiItem("☠️", "Skull and Crossbones", EmojiCategory.SMILEYS, listOf("danger", "poison", "pirate")),
        EmojiItem("💩", "Pile of Poo", EmojiCategory.SMILEYS, listOf("poop", "poo", "crap")),
        EmojiItem("🤡", "Clown Face", EmojiCategory.SMILEYS, listOf("clown", "circus", "fool")),
        EmojiItem("👻", "Ghost", EmojiCategory.SMILEYS, listOf("ghost", "halloween", "spooky")),
        EmojiItem("👽", "Alien", EmojiCategory.SMILEYS, listOf("alien", "ufo", "space")),
        EmojiItem("🤖", "Robot", EmojiCategory.SMILEYS, listOf("robot", "bot", "ai")),
        EmojiItem("❤️", "Red Heart", EmojiCategory.SMILEYS, listOf("love", "heart", "like")),
        EmojiItem("🧡", "Orange Heart", EmojiCategory.SMILEYS, listOf("love", "heart")),
        EmojiItem("💛", "Yellow Heart", EmojiCategory.SMILEYS, listOf("love", "friendship")),
        EmojiItem("💚", "Green Heart", EmojiCategory.SMILEYS, listOf("love", "nature")),
        EmojiItem("💙", "Blue Heart", EmojiCategory.SMILEYS, listOf("love", "peace")),
        EmojiItem("💜", "Purple Heart", EmojiCategory.SMILEYS, listOf("love", "purple")),
        EmojiItem("🖤", "Black Heart", EmojiCategory.SMILEYS, listOf("dark", "heart")),
        EmojiItem("🤍", "White Heart", EmojiCategory.SMILEYS, listOf("pure", "heart")),
        EmojiItem("💔", "Broken Heart", EmojiCategory.SMILEYS, listOf("breakup", "heartbreak", "sad")),
        EmojiItem("❤️‍🔥", "Heart on Fire", EmojiCategory.SMILEYS, listOf("passion", "fire", "love")),
        EmojiItem("✨", "Sparkles", EmojiCategory.SMILEYS, listOf("magic", "stars", "sparkle", "clean")),
        EmojiItem("🔥", "Fire", EmojiCategory.SMILEYS, listOf("hot", "flame", "lit", "fire", "burn")),

        // People & Body
        EmojiItem("👋", "Waving Hand", EmojiCategory.PEOPLE, listOf("hello", "hi", "bye", "wave"), supportsSkinTone = true),
        EmojiItem("🤚", "Raised Back of Hand", EmojiCategory.PEOPLE, listOf("backhand", "raised"), supportsSkinTone = true),
        EmojiItem("🖐️", "Hand with Fingers Splayed", EmojiCategory.PEOPLE, listOf("hand", "five"), supportsSkinTone = true),
        EmojiItem("✋", "Raised Hand", EmojiCategory.PEOPLE, listOf("high five", "stop", "hand"), supportsSkinTone = true),
        EmojiItem("🖖", "Vulcan Salute", EmojiCategory.PEOPLE, listOf("spock", "star trek"), supportsSkinTone = true),
        EmojiItem("🫱", "Rightwards Hand", EmojiCategory.PEOPLE, listOf("hand", "reach"), supportsSkinTone = true),
        EmojiItem("🫲", "Leftwards Hand", EmojiCategory.PEOPLE, listOf("hand", "reach"), supportsSkinTone = true),
        EmojiItem("👌", "OK Hand", EmojiCategory.PEOPLE, listOf("okay", "perfect", "good"), supportsSkinTone = true),
        EmojiItem("🤌", "Pinched Fingers", EmojiCategory.PEOPLE, listOf("italian", "what do you want"), supportsSkinTone = true),
        EmojiItem("🤏", "Pinching Hand", EmojiCategory.PEOPLE, listOf("little", "small", "tiny"), supportsSkinTone = true),
        EmojiItem("✌️", "Victory Hand", EmojiCategory.PEOPLE, listOf("peace", "two", "victory"), supportsSkinTone = true),
        EmojiItem("🤞", "Crossed Fingers", EmojiCategory.PEOPLE, listOf("luck", "hope"), supportsSkinTone = true),
        EmojiItem("🫰", "Hand with Index Finger and Thumb Crossed", EmojiCategory.PEOPLE, listOf("finger heart", "money"), supportsSkinTone = true),
        EmojiItem("🤟", "Love-You Gesture", EmojiCategory.PEOPLE, listOf("ily", "love"), supportsSkinTone = true),
        EmojiItem("🤘", "Sign of the Horns", EmojiCategory.PEOPLE, listOf("rock on", "metal"), supportsSkinTone = true),
        EmojiItem("🤙", "Call Me Hand", EmojiCategory.PEOPLE, listOf("shaka", "call me"), supportsSkinTone = true),
        EmojiItem("👈", "Backhand Index Pointing Left", EmojiCategory.PEOPLE, listOf("point left"), supportsSkinTone = true),
        EmojiItem("👉", "Backhand Index Pointing Right", EmojiCategory.PEOPLE, listOf("point right"), supportsSkinTone = true),
        EmojiItem("👆", "Backhand Index Pointing Up", EmojiCategory.PEOPLE, listOf("point up"), supportsSkinTone = true),
        EmojiItem("👇", "Backhand Index Pointing Down", EmojiCategory.PEOPLE, listOf("point down"), supportsSkinTone = true),
        EmojiItem("☝️", "Index Pointing Up", EmojiCategory.PEOPLE, listOf("one", "point up"), supportsSkinTone = true),
        EmojiItem("👍", "Thumbs Up", EmojiCategory.PEOPLE, listOf("like", "good", "yes", "approve", "thumbs up"), supportsSkinTone = true),
        EmojiItem("👎", "Thumbs Down", EmojiCategory.PEOPLE, listOf("dislike", "bad", "no"), supportsSkinTone = true),
        EmojiItem("✊", "Raised Fist", EmojiCategory.PEOPLE, listOf("fist", "power"), supportsSkinTone = true),
        EmojiItem("👊", "Oncoming Fist", EmojiCategory.PEOPLE, listOf("punch", "fist bump"), supportsSkinTone = true),
        EmojiItem("👏", "Clapping Hands", EmojiCategory.PEOPLE, listOf("applause", "bravo", "clap"), supportsSkinTone = true),
        EmojiItem("🙌", "Raising Hands", EmojiCategory.PEOPLE, listOf("celebrate", "praise", "hurray"), supportsSkinTone = true),
        EmojiItem("🫶", "Heart Hands", EmojiCategory.PEOPLE, listOf("love", "heart", "care"), supportsSkinTone = true),
        EmojiItem("👐", "Open Hands", EmojiCategory.PEOPLE, listOf("open hands", "hug"), supportsSkinTone = true),
        EmojiItem("🤲", "Palms Up Together", EmojiCategory.PEOPLE, listOf("pray", "dua"), supportsSkinTone = true),
        EmojiItem("🤝", "Handshake", EmojiCategory.PEOPLE, listOf("agreement", "deal", "meeting")),
        EmojiItem("🙏", "Folded Hands", EmojiCategory.PEOPLE, listOf("pray", "thank you", "please", "namaste"), supportsSkinTone = true),
        EmojiItem("✍️", "Writing Hand", EmojiCategory.PEOPLE, listOf("write", "pen"), supportsSkinTone = true),
        EmojiItem("💅", "Nail Polish", EmojiCategory.PEOPLE, listOf("beauty", "nails", "sassy"), supportsSkinTone = true),
        EmojiItem("🤳", "Selfie", EmojiCategory.PEOPLE, listOf("camera", "selfie", "phone"), supportsSkinTone = true),
        EmojiItem("💪", "Flexed Biceps", EmojiCategory.PEOPLE, listOf("strong", "muscle", "workout", "flex"), supportsSkinTone = true),
        EmojiItem("👀", "Eyes", EmojiCategory.PEOPLE, listOf("look", "see", "watch", "eyes")),
        EmojiItem("👶", "Baby", EmojiCategory.PEOPLE, listOf("child", "infant"), supportsSkinTone = true),
        EmojiItem("👧", "Girl", EmojiCategory.PEOPLE, listOf("girl", "female"), supportsSkinTone = true),
        EmojiItem("🧒", "Child", EmojiCategory.PEOPLE, listOf("child", "kid"), supportsSkinTone = true),
        EmojiItem("👦", "Boy", EmojiCategory.PEOPLE, listOf("boy", "male"), supportsSkinTone = true),
        EmojiItem("👩", "Woman", EmojiCategory.PEOPLE, listOf("female", "lady"), supportsSkinTone = true),
        EmojiItem("🧑", "Person", EmojiCategory.PEOPLE, listOf("adult", "human"), supportsSkinTone = true),
        EmojiItem("👨", "Man", EmojiCategory.PEOPLE, listOf("male", "guy"), supportsSkinTone = true),
        EmojiItem("🧑‍💻", "Technologist", EmojiCategory.PEOPLE, listOf("coder", "developer", "hacker", "programmer"), supportsSkinTone = true),
        EmojiItem("💃", "Woman Dancing", EmojiCategory.PEOPLE, listOf("dance", "salsa"), supportsSkinTone = true),
        EmojiItem("🕺", "Man Dancing", EmojiCategory.PEOPLE, listOf("dance", "disco"), supportsSkinTone = true),

        // Animals & Nature
        EmojiItem("🐶", "Dog Face", EmojiCategory.ANIMALS, listOf("dog", "puppy", "pet")),
        EmojiItem("🐱", "Cat Face", EmojiCategory.ANIMALS, listOf("cat", "kitten", "pet")),
        EmojiItem("🐭", "Mouse Face", EmojiCategory.ANIMALS, listOf("mouse", "rodent")),
        EmojiItem("🐹", "Hamster", EmojiCategory.ANIMALS, listOf("hamster", "pet")),
        EmojiItem("🐰", "Rabbit Face", EmojiCategory.ANIMALS, listOf("bunny", "rabbit")),
        EmojiItem("🦊", "Fox", EmojiCategory.ANIMALS, listOf("fox", "wild")),
        EmojiItem("🐻", "Bear", EmojiCategory.ANIMALS, listOf("bear", "wild")),
        EmojiItem("🐼", "Panda", EmojiCategory.ANIMALS, listOf("panda", "bear")),
        EmojiItem("🐨", "Koala", EmojiCategory.ANIMALS, listOf("koala", "australia")),
        EmojiItem("🐯", "Tiger Face", EmojiCategory.ANIMALS, listOf("tiger", "cat")),
        EmojiItem("🦁", "Lion", EmojiCategory.ANIMALS, listOf("lion", "king")),
        EmojiItem("🐮", "Cow Face", EmojiCategory.ANIMALS, listOf("cow", "beef", "milk")),
        EmojiItem("🐷", "Pig Face", EmojiCategory.ANIMALS, listOf("pig", "pork")),
        EmojiItem("🐸", "Frog", EmojiCategory.ANIMALS, listOf("frog", "toad")),
        EmojiItem("🐵", "Monkey Face", EmojiCategory.ANIMALS, listOf("monkey", "ape")),
        EmojiItem("🐔", "Chicken", EmojiCategory.ANIMALS, listOf("chicken", "bird")),
        EmojiItem("🐧", "Penguin", EmojiCategory.ANIMALS, listOf("penguin", "antarctica")),
        EmojiItem("🐦", "Bird", EmojiCategory.ANIMALS, listOf("bird", "nature")),
        EmojiItem("🦅", "Eagle", EmojiCategory.ANIMALS, listOf("eagle", "bird")),
        EmojiItem("🦆", "Duck", EmojiCategory.ANIMALS, listOf("duck", "bird")),
        EmojiItem("🦉", "Owl", EmojiCategory.ANIMALS, listOf("owl", "wise")),
        EmojiItem("🦇", "Bat", EmojiCategory.ANIMALS, listOf("bat", "vampire")),
        EmojiItem("🐺", "Wolf", EmojiCategory.ANIMALS, listOf("wolf", "howl")),
        EmojiItem("🐴", "Horse Face", EmojiCategory.ANIMALS, listOf("horse", "pony")),
        EmojiItem("🦄", "Unicorn", EmojiCategory.ANIMALS, listOf("unicorn", "magic")),
        EmojiItem("🐝", "Honeybee", EmojiCategory.ANIMALS, listOf("bee", "honey")),
        EmojiItem("🐛", "Bug", EmojiCategory.ANIMALS, listOf("bug", "insect")),
        EmojiItem("🦋", "Butterfly", EmojiCategory.ANIMALS, listOf("butterfly", "insect")),
        EmojiItem("🐌", "Snail", EmojiCategory.ANIMALS, listOf("snail", "slow")),
        EmojiItem("🐞", "Lady Beetle", EmojiCategory.ANIMALS, listOf("ladybug", "insect")),
        EmojiItem("🐜", "Ant", EmojiCategory.ANIMALS, listOf("ant", "insect")),
        EmojiItem("🕷️", "Spider", EmojiCategory.ANIMALS, listOf("spider", "web")),
        EmojiItem("🌸", "Cherry Blossom", EmojiCategory.ANIMALS, listOf("flower", "sakura", "spring")),
        EmojiItem("🌹", "Rose", EmojiCategory.ANIMALS, listOf("flower", "rose", "romantic")),
        EmojiItem("🌺", "Hibiscus", EmojiCategory.ANIMALS, listOf("flower", "tropical")),
        EmojiItem("🌻", "Sunflower", EmojiCategory.ANIMALS, listOf("flower", "sunflower", "summer")),
        EmojiItem("🌲", "Evergreen Tree", EmojiCategory.ANIMALS, listOf("tree", "forest", "pine")),
        EmojiItem("🌴", "Palm Tree", EmojiCategory.ANIMALS, listOf("tree", "beach", "tropical")),
        EmojiItem("🍀", "Four Leaf Clover", EmojiCategory.ANIMALS, listOf("clover", "luck", "irish")),

        // Food & Drink
        EmojiItem("🍏", "Green Apple", EmojiCategory.FOOD, listOf("apple", "fruit")),
        EmojiItem("🍎", "Red Apple", EmojiCategory.FOOD, listOf("apple", "fruit")),
        EmojiItem("🍐", "Pear", EmojiCategory.FOOD, listOf("pear", "fruit")),
        EmojiItem("🍊", "Tangerine", EmojiCategory.FOOD, listOf("orange", "fruit", "citrus")),
        EmojiItem("🍋", "Lemon", EmojiCategory.FOOD, listOf("lemon", "sour")),
        EmojiItem("🍌", "Banana", EmojiCategory.FOOD, listOf("banana", "fruit")),
        EmojiItem("🍉", "Watermelon", EmojiCategory.FOOD, listOf("watermelon", "fruit")),
        EmojiItem("🍇", "Grapes", EmojiCategory.FOOD, listOf("grapes", "fruit")),
        EmojiItem("🍓", "Strawberry", EmojiCategory.FOOD, listOf("berry", "fruit")),
        EmojiItem("🫐", "Blueberries", EmojiCategory.FOOD, listOf("berry", "fruit")),
        EmojiItem("🍒", "Cherries", EmojiCategory.FOOD, listOf("cherry", "fruit")),
        EmojiItem("🍑", "Peach", EmojiCategory.FOOD, listOf("peach", "fruit", "butt")),
        EmojiItem("🥭", "Mango", EmojiCategory.FOOD, listOf("mango", "fruit")),
        EmojiItem("🍍", "Pineapple", EmojiCategory.FOOD, listOf("pineapple", "fruit")),
        EmojiItem("🥥", "Coconut", EmojiCategory.FOOD, listOf("coconut", "tropical")),
        EmojiItem("🥝", "Kiwi Fruit", EmojiCategory.FOOD, listOf("kiwi", "fruit")),
        EmojiItem("🥑", "Avocado", EmojiCategory.FOOD, listOf("avocado", "guacamole")),
        EmojiItem("🍕", "Pizza", EmojiCategory.FOOD, listOf("pizza", "cheese", "italian")),
        EmojiItem("🍔", "Hamburger", EmojiCategory.FOOD, listOf("burger", "fast food")),
        EmojiItem("🍟", "French Fries", EmojiCategory.FOOD, listOf("fries", "fast food")),
        EmojiItem("🌭", "Hot Dog", EmojiCategory.FOOD, listOf("hotdog", "sausage")),
        EmojiItem("🥪", "Sandwich", EmojiCategory.FOOD, listOf("sandwich", "lunch")),
        EmojiItem("🌮", "Taco", EmojiCategory.FOOD, listOf("taco", "mexican")),
        EmojiItem("🌯", "Burrito", EmojiCategory.FOOD, listOf("burrito", "mexican")),
        EmojiItem("🍣", "Sushi", EmojiCategory.FOOD, listOf("sushi", "japanese")),
        EmojiItem("🍦", "Soft Ice Cream", EmojiCategory.FOOD, listOf("ice cream", "dessert")),
        EmojiItem("🍩", "Doughnut", EmojiCategory.FOOD, listOf("donut", "dessert")),
        EmojiItem("🍪", "Cookie", EmojiCategory.FOOD, listOf("cookie", "biscuit")),
        EmojiItem("🎂", "Birthday Cake", EmojiCategory.FOOD, listOf("cake", "birthday")),
        EmojiItem("☕", "Hot Beverage", EmojiCategory.FOOD, listOf("coffee", "tea", "cafe")),
        EmojiItem("🍵", "Teacup Without Handle", EmojiCategory.FOOD, listOf("tea", "matcha")),
        EmojiItem("🍺", "Beer Mug", EmojiCategory.FOOD, listOf("beer", "drink", "pub")),
        EmojiItem("🍷", "Wine Glass", EmojiCategory.FOOD, listOf("wine", "drink")),

        // Travel & Places
        EmojiItem("🚗", "Automobile", EmojiCategory.TRAVEL, listOf("car", "drive", "vehicle")),
        EmojiItem("🚕", "Taxi", EmojiCategory.TRAVEL, listOf("cab", "taxi")),
        EmojiItem("🚙", "Sport Utility Vehicle", EmojiCategory.TRAVEL, listOf("suv", "car")),
        EmojiItem("🚌", "Bus", EmojiCategory.TRAVEL, listOf("bus", "transit")),
        EmojiItem("🏎️", "Racing Car", EmojiCategory.TRAVEL, listOf("race", "fast", "f1")),
        EmojiItem("🚓", "Police Car", EmojiCategory.TRAVEL, listOf("police", "cop")),
        EmojiItem("🚑", "Ambulance", EmojiCategory.TRAVEL, listOf("emergency", "hospital")),
        EmojiItem("🚒", "Fire Engine", EmojiCategory.TRAVEL, listOf("fire truck")),
        EmojiItem("🚲", "Bicycle", EmojiCategory.TRAVEL, listOf("bike", "cycle")),
        EmojiItem("🛵", "Motor Scooter", EmojiCategory.TRAVEL, listOf("vespa", "scooter")),
        EmojiItem("✈️", "Airplane", EmojiCategory.TRAVEL, listOf("plane", "flight", "travel")),
        EmojiItem("🚀", "Rocket", EmojiCategory.TRAVEL, listOf("space", "moon", "launch")),
        EmojiItem("🛸", "Flying Saucer", EmojiCategory.TRAVEL, listOf("ufo", "alien")),
        EmojiItem("🚢", "Ship", EmojiCategory.TRAVEL, listOf("boat", "cruise")),
        EmojiItem("🏖️", "Beach with Umbrella", EmojiCategory.TRAVEL, listOf("beach", "sea", "vacation")),
        EmojiItem("🏝️", "Desert Island", EmojiCategory.TRAVEL, listOf("island", "tropical")),
        EmojiItem("🏔️", "Snow-Capped Mountain", EmojiCategory.TRAVEL, listOf("mountain", "snow")),
        EmojiItem("🏕️", "Camping", EmojiCategory.TRAVEL, listOf("camp", "tent")),

        // Activities
        EmojiItem("⚽", "Soccer Ball", EmojiCategory.ACTIVITIES, listOf("soccer", "football", "sport")),
        EmojiItem("🏀", "Basketball", EmojiCategory.ACTIVITIES, listOf("basketball", "nba", "sport")),
        EmojiItem("🏈", "American Football", EmojiCategory.ACTIVITIES, listOf("football", "nfl", "sport")),
        EmojiItem("⚾", "Baseball", EmojiCategory.ACTIVITIES, listOf("baseball", "mlb")),
        EmojiItem("🎾", "Tennis", EmojiCategory.ACTIVITIES, listOf("tennis", "ball")),
        EmojiItem("🏐", "Volleyball", EmojiCategory.ACTIVITIES, listOf("volleyball")),
        EmojiItem("🎱", "Pool 8 Ball", EmojiCategory.ACTIVITIES, listOf("billiards", "pool")),
        EmojiItem("🎮", "Video Game", EmojiCategory.ACTIVITIES, listOf("controller", "game", "gaming")),
        EmojiItem("🎲", "Game Die", EmojiCategory.ACTIVITIES, listOf("dice", "board game")),
        EmojiItem("🎯", "Bullseye", EmojiCategory.ACTIVITIES, listOf("target", "darts", "goal")),
        EmojiItem("🎨", "Artist Palette", EmojiCategory.ACTIVITIES, listOf("art", "paint", "design")),
        EmojiItem("🎬", "Clapper Board", EmojiCategory.ACTIVITIES, listOf("movie", "film")),
        EmojiItem("🎤", "Microphone", EmojiCategory.ACTIVITIES, listOf("sing", "karaoke")),
        EmojiItem("🎧", "Headphone", EmojiCategory.ACTIVITIES, listOf("music", "listen")),
        EmojiItem("🎸", "Guitar", EmojiCategory.ACTIVITIES, listOf("music", "rock")),

        // Objects
        EmojiItem("📱", "Mobile Phone", EmojiCategory.OBJECTS, listOf("phone", "iphone", "smartphone")),
        EmojiItem("💻", "Laptop", EmojiCategory.OBJECTS, listOf("computer", "macbook", "pc")),
        EmojiItem("⌨️", "Keyboard", EmojiCategory.OBJECTS, listOf("type", "computer", "keyboard")),
        EmojiItem("🖥️", "Desktop Computer", EmojiCategory.OBJECTS, listOf("screen", "monitor")),
        EmojiItem("📷", "Camera", EmojiCategory.OBJECTS, listOf("photo", "picture")),
        EmojiItem("💡", "Light Bulb", EmojiCategory.OBJECTS, listOf("idea", "light")),
        EmojiItem("🔦", "Flashlight", EmojiCategory.OBJECTS, listOf("torch", "light")),
        EmojiItem("📖", "Open Book", EmojiCategory.OBJECTS, listOf("read", "study", "book")),
        EmojiItem("💰", "Money Bag", EmojiCategory.OBJECTS, listOf("cash", "wealth", "money")),
        EmojiItem("💳", "Credit Card", EmojiCategory.OBJECTS, listOf("payment", "money")),
        EmojiItem("💎", "Gem Stone", EmojiCategory.OBJECTS, listOf("diamond", "jewel")),
        EmojiItem("🔑", "Key", EmojiCategory.OBJECTS, listOf("lock", "password")),
        EmojiItem("🔒", "Locked", EmojiCategory.OBJECTS, listOf("security", "private")),
        EmojiItem("📦", "Package", EmojiCategory.OBJECTS, listOf("box", "delivery")),
        EmojiItem("✉️", "Envelope", EmojiCategory.OBJECTS, listOf("mail", "email", "letter")),

        // Symbols
        EmojiItem("❤️", "Red Heart", EmojiCategory.SYMBOLS, listOf("love", "heart")),
        EmojiItem("☮️", "Peace Symbol", EmojiCategory.SYMBOLS, listOf("peace")),
        EmojiItem("✝️", "Latin Cross", EmojiCategory.SYMBOLS, listOf("christian", "cross")),
        EmojiItem("☪️", "Star and Crescent", EmojiCategory.SYMBOLS, listOf("islam", "muslim")),
        EmojiItem("🕉️", "Om", EmojiCategory.SYMBOLS, listOf("hindu", "om")),
        EmojiItem("✡️", "Star of David", EmojiCategory.SYMBOLS, listOf("jewish")),
        EmojiItem("☸️", "Wheel of Dharma", EmojiCategory.SYMBOLS, listOf("buddhist")),
        EmojiItem("☯️", "Yin Yang", EmojiCategory.SYMBOLS, listOf("balance")),
        EmojiItem("♾️", "Infinity", EmojiCategory.SYMBOLS, listOf("forever", "limitless")),
        EmojiItem("⚠️", "Warning", EmojiCategory.SYMBOLS, listOf("caution", "alert")),
        EmojiItem("⛔", "No Entry", EmojiCategory.SYMBOLS, listOf("stop", "forbidden")),
        EmojiItem("🚫", "Prohibited", EmojiCategory.SYMBOLS, listOf("no", "ban")),
        EmojiItem("✅", "Check Mark Button", EmojiCategory.SYMBOLS, listOf("done", "yes", "correct")),
        EmojiItem("❌", "Cross Mark", EmojiCategory.SYMBOLS, listOf("wrong", "no", "x")),
        EmojiItem("❓", "Question Mark", EmojiCategory.SYMBOLS, listOf("ask", "what")),
        EmojiItem("❗", "Exclamation Mark", EmojiCategory.SYMBOLS, listOf("alert", "important")),
        EmojiItem("💯", "Hundred Points", EmojiCategory.SYMBOLS, listOf("perfect", "100", "score")),
        EmojiItem("🎵", "Musical Note", EmojiCategory.SYMBOLS, listOf("music", "song")),
        EmojiItem("🎶", "Musical Notes", EmojiCategory.SYMBOLS, listOf("music", "melody")),

        // Flags
        EmojiItem("🇺🇸", "Flag: United States", EmojiCategory.FLAGS, listOf("america", "usa")),
        EmojiItem("🇬🇧", "Flag: United Kingdom", EmojiCategory.FLAGS, listOf("uk", "britain")),
        EmojiItem("🇨🇦", "Flag: Canada", EmojiCategory.FLAGS, listOf("canada")),
        EmojiItem("🇦🇺", "Flag: Australia", EmojiCategory.FLAGS, listOf("australia")),
        EmojiItem("🇩🇪", "Flag: Germany", EmojiCategory.FLAGS, listOf("germany", "deutschland")),
        EmojiItem("🇫🇷", "Flag: France", EmojiCategory.FLAGS, listOf("france")),
        EmojiItem("🇪🇸", "Flag: Spain", EmojiCategory.FLAGS, listOf("spain", "espana")),
        EmojiItem("🇮🇹", "Flag: Italy", EmojiCategory.FLAGS, listOf("italy", "italia")),
        EmojiItem("🇯🇵", "Flag: Japan", EmojiCategory.FLAGS, listOf("japan")),
        EmojiItem("🇰🇷", "Flag: South Korea", EmojiCategory.FLAGS, listOf("korea")),
        EmojiItem("🇨🇳", "Flag: China", EmojiCategory.FLAGS, listOf("china")),
        EmojiItem("🇮🇳", "Flag: India", EmojiCategory.FLAGS, listOf("india")),
        EmojiItem("🇧🇷", "Flag: Brazil", EmojiCategory.FLAGS, listOf("brazil")),
        EmojiItem("🇲🇽", "Flag: Mexico", EmojiCategory.FLAGS, listOf("mexico")),
        EmojiItem("🇷🇺", "Flag: Russia", EmojiCategory.FLAGS, listOf("russia")),
        EmojiItem("🇸🇦", "Flag: Saudi Arabia", EmojiCategory.FLAGS, listOf("saudi")),
        EmojiItem("🇦🇪", "Flag: United Arab Emirates", EmojiCategory.FLAGS, listOf("uae", "dubai")),
        EmojiItem("🏳️‍🌈", "Rainbow Flag", EmojiCategory.FLAGS, listOf("pride", "lgbt"))
    )

    fun getEmojisForCategory(category: EmojiCategory): List<EmojiItem> {
        return allEmojis.filter { it.category == category }
    }

    fun search(query: String): List<EmojiItem> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return allEmojis
        return allEmojis.filter { it.matchesQuery(q) }
    }
}
